#ifndef __DFFPanel__
#define __DFFPanel__

/**
@file
Subclass of DFFPanelPrototype, which is generated by wxFormBuilder.
*/

#include "../WxGUI.h"
#include <dff/DFFMesh.h>

/** Implementing DFFPanelPrototype */
class DFFPanel : public DFFPanelPrototype
{
public:
	/** Constructor */
	DFFPanel( wxWindow* parent );

protected:
	virtual bool doDisplay(DataSource* source);
	virtual void doClose();
	void onFrameSelectionChanged(wxCommandEvent& evt);
	void onGeometrySelectionChanged(wxCommandEvent& evt);
	void onGeometryPartSelectionChanged(wxCommandEvent& evt);
	void onGeometryMaterialSelectionChanged(wxCommandEvent& evt);
	void onGeometryMaterialTextureSelectionChanged(wxCommandEvent& evt);

private:
	DFFMesh* mesh;
};

#endif // __DFFPanel__
