#ifndef __AboutFrame__
#define __AboutFrame__

/**
@file
Subclass of AboutFramePrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"
#include "guiconfig.h"

/** Implementing AboutFramePrototype */
class AboutFrame : public AboutFramePrototype
{
public:
	/** Constructor */
	AboutFrame( wxWindow* parent );
};

#endif // __AboutFrame__
