#ifndef __IMGPanel__
#define __IMGPanel__

#include <fstream>
#include <gtaformats/IMGArchive.h>
#include "FileDisplayer.h"

using std::ifstream;

/**
@file
Subclass of IMGPanelPrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing IMGPanelPrototype */
class IMGPanel : public IMGPanelPrototype
{
protected:
	virtual void onSelectionChanged(wxCommandEvent& evt);

public:
	static bool canDisplay(const wxString& filename);

public:
	//IMGPanel(wxWindow* parent, wxMenu* menu, wxMenu* txdMenu);
	//bool displayFile(const char* filename);
	//virtual ~IMGPanel();
	IMGPanel(wxWindow* parent);
	virtual ~IMGPanel();
	virtual bool doDisplay(istream* stream);
	virtual void doClose();

private:
	//wxMenu* menu;
	//wxMenu* txdMenu;
	//ifstream* stream;
	IMGArchive* archive;
	FileDisplayer* entryDisplayer;
	//wxWindow* pluginWindow;
};

#endif // __IMGPanel__
