#ifndef __IMGPanel__
#define __IMGPanel__

#include <fstream>
#include <gtaformats/IMGArchive.h>

using std::ifstream;

/**
@file
Subclass of IMGPanelPrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing IMGPanelPrototype */
class IMGPanel : public IMGPanelPrototype
{
protected:
	virtual void onSelectionChanged(wxCommandEvent& evt);

public:
	/** Constructor */
	IMGPanel(wxWindow* parent, const char* filename, wxMenu* menu, wxMenu* txdMenu);
	virtual ~IMGPanel();

private:
	wxMenu* menu;
	wxMenu* txdMenu;
	ifstream* stream;
	IMGArchive* archive;
	wxWindow* pluginWindow;
};

#endif // __IMGPanel__
