#ifndef __TXDPanel__
#define __TXDPanel__

#include <gtaformats/TXDArchive.h>
#include <fstream>
#include <istream>
#include "guiconfig.h"
#include "lang/lang.h"

using std::ifstream;
using std::istream;

/**
@file
Subclass of TXDPanelPrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing TXDPanelPrototype */
class TXDPanel : public TXDPanelPrototype
{
protected:
	void onTextureSelectionChanged(wxCommandEvent& evt);
	void onExtract(wxCommandEvent& evt);

public:
	/** Constructor */
	TXDPanel(wxWindow* parent, wxWindow* window, istream* stream, wxMenu* menu,
			bool autoCloseStream = false);
	//TXDPanel(wxWindow* parent, MainFrame* mainFrame, const char* filename, wxMenu* menu);
	virtual ~TXDPanel();
	void displayArchive(TXDArchive* archive);

private:
	void displayTexture(TXDTexture* texture);

private:
	wxMenu* menu;
	TXDArchive* archive;
	istream* stream;
	bool autoCloseStream;
};

#endif // __TXDPanel__
