/*
	Copyright 2010 David Lerch

	This file is part of gtatools-gui.

	gtatools-gui is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	gtatools-gui is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with gtatools-gui.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFramePrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing MainFramePrototype */
class MainFrame : public MainFramePrototype
{
protected:
	// Handlers for MainFramePrototype events.
	void onOpen(wxCommandEvent& event);
	void onClose(wxCommandEvent& evt);
	void onAbout(wxCommandEvent& evt);
	
public:
	static MainFrame* getInstance();

public:
	void displayFile(const wxString& filename);

private:
	MainFrame( wxWindow* parent );

private:
	FileDisplayer* displayer;
};

#endif // __MainFrame__
