#ifndef __DFFPanel__
#define __DFFPanel__

/**
@file
Subclass of DFFPanelPrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing DFFPanelPrototype */
class DFFPanel : public DFFPanelPrototype
{
public:
	/** Constructor */
	DFFPanel( wxWindow* parent );
};

#endif // __DFFPanel__
