#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFramePrototype, which is generated by wxFormBuilder.
*/

#include "WxGUI.h"

/** Implementing MainFramePrototype */
class MainFrame : public MainFramePrototype
{
protected:
	// Handlers for MainFramePrototype events.
	void onOpen( wxCommandEvent& event );
	void onClose(wxCommandEvent& evt);
	
public:
	/** Constructor */
	MainFrame( wxWindow* parent );
	void displayFile(const wxString& filename);

private:
	FileDisplayer* displayer;
};

#endif // __MainFrame__
