/*
	Copyright 2010 David Lerch

	This file is part of gtatools-gui.

	gtatools-gui is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	gtatools-gui is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with gtatools-gui.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __DFFPanel__
#define __DFFPanel__

/**
@file
Subclass of DFFPanelPrototype, which is generated by wxFormBuilder.
*/

#include "../WxGUI.h"
#include <gtaformats/dff/DFFMesh.h>

/** Implementing DFFPanelPrototype */
class DFFPanel : public DFFPanelPrototype
{
public:
	/** Constructor */
	DFFPanel( wxWindow* parent );

protected:
	virtual bool doDisplay(DataSource* source);
	virtual void doClose();
	void onFrameSelectionChanged(wxCommandEvent& evt);
	void onGeometrySelectionChanged(wxCommandEvent& evt);
	void onGeometryPartSelectionChanged(wxCommandEvent& evt);
	void onGeometryMaterialSelectionChanged(wxCommandEvent& evt);
	void onGeometryMaterialTextureSelectionChanged(wxCommandEvent& evt);

private:
	DFFMesh* mesh;
};

#endif // __DFFPanel__
